FROM osrf/ros:humble-desktop-full
ARG QT_VERSION=6.6.1
ARG QT_MODULES="qtlocation qtpositioning qtspeech qt5compat qtquick3d qtmultimedia qtserialport qtcharts qtshadertools"

ENV DEBIAN_FRONTEND noninteractive

ENV DISPLAY :99
ENV LANG en_US.UTF-8
ENV QMAKESPEC linux-g++-64

ENV QT_PATH /opt/Qt
ENV QT_DESKTOP $QT_PATH/${QT_VERSION}/gcc_64

ENV PATH /usr/lib/ccache:$QT_DESKTOP/bin:$PATH

RUN apt-get update && apt-get -y --quiet --no-install-recommends install \
		apt-utils \
		binutils \
		build-essential \
		ca-certificates \
		ccache \
		checkinstall \
		cmake \
		curl \
		espeak \
		fuse \
		g++ \
		gcc \
		git \
		gosu \
		kmod \
		libespeak-dev \
		libfontconfig1 \
		libfuse2 \
		libgstreamer-plugins-base1.0-dev \
		libgstreamer1.0-0 \
		libgstreamer1.0-dev \
		libsdl2-dev \
		libssl-dev \
		libudev-dev \
		locales \
		make \
		ninja-build \
		openssh-client \
		openssl \
		patchelf \
		pkg-config \
		rsync \
		speech-dispatcher \
		wget \
		xvfb \
		zlib1g-dev \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*


RUN apt-get install python3-pip -y
RUN pip3 install --user PySide2
RUN apt-get update && apt-get install wget

WORKDIR /workdir
RUN wget https://d176tv9ibo4jno.cloudfront.net/latest/QGroundControl.AppImage
RUN chmod +x ./QGroundControl.AppImage

RUN useradd user --create-home --home-dir /home/user --shell /bin/bash --uid 1000
USER user
CMD [ "bash" ]